on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: |
          git config user.name 'github-actions'
          git config user.email '/'
          yarn
          yarn release
          rm README.md
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          git push origin main --follow-tags
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const tag = require("child_process").execSync("git describe").toString().trim();
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: tag,
              generate_release_notes: true
            });